//1. Imprimir a mensagem: “É PRECISO FAZER TODOS OS ALGORITMOS PARA APRENDER, NADA DE COPIAR DO COLEGA!” 

System.Console.Write("É PRECISO FAZER TODOS OS ALGORITMOS PARA APRENDER, NADA DE COPIAR DO COLEGA!")